### ISSUE TITLE
Implement bit.ly

### ISSUE THREAD

**Issue by empeje** [kulkultech/ngecilin#2]
- [ ] In the options page, user can set their default URL shortener provider e.g. TinyURL, BitLy, and Short.io
- [ ] If the BitLy is chosen, the user should give their **access token**.
- [ ] When using the main pop-up, we will generate link using BitLy API

**Comment by galanggg** [comment]
Halo mas @empeje how I can help with this one ?

**Comment by empeje** [comment]
Hi @galanggg thank you for reaching me, as mentioned above, you can start forking the repository and then start implementing a description on the issue description. Is the description clear enough for you?

**Comment by galanggg** [comment]
Okay, I will try it first @empeje, for the BitLy we need to store the token for auth right ?

**Comment by empeje** [comment]
Yes @galanggg, so imagine we have *options page*, the user will set bit.ly setting from *options page* and then we in the *popup menu* it will show the same interface.


In the *options page*:
* Ability to set which provider we're using (only 1 provider can active at one time)
* Ability to set the config for the provider we choose.

In the *popup menu*:

We'll use the API for the provider selected, so by default, it will use TinyURL, and later if in the options page bit.ly is active the *popup* will use the bit.ly.

**Comment by empeje** [comment]
Hi, @galanggg are you still on with this issue?

**Comment by galanggg** [comment]
Hi mas @empeje, sorry my progress is a bit slow. But I just finished the script for bit.ly, [https://gist.github.com/galanggg/8f00cb52c98e950ad77c3e8149a1eee7](url) please kindly to check mas thanks.

**Comment by galanggg** [comment]
and for the `group_guid` we must made a `GET` request to https://api-ssl.bitly.com/v4/groups endpoint for getting the unique `group_guid`

**Comment by empeje** [comment]
Hi @galanggg no worries, we're not in hurry. BTW you can create a draft Pull Request as well to reduce double work from other people. the script looks good as well.

**Comment by empeje** [comment]
You can use this client for BitLy https://github.com/kulkultech/bitly-client
