### ISSUE TITLE
Implement a new ngecilin icon

### ISSUE THREAD

**Issue by hudakurniawan** [kulkultech/ngecilin#27]
Implement a new ngecilin icon using the following sets.

16 ![favico-ngecilin-16](https://user-images.githubusercontent.com/17465294/100256225-2008e680-2f77-11eb-9a0a-975ddb9a1a1b.png)

32 ![favico-ngecilin-32](https://user-images.githubusercontent.com/17465294/100256229-213a1380-2f77-11eb-9db5-5f7c0a06712c.png)

48 ![favico-ngecilin-48](https://user-images.githubusercontent.com/17465294/100256231-21d2aa00-2f77-11eb-8477-7a1dcb4ad87e.png)

64 ![favico-ngecilin-64](https://user-images.githubusercontent.com/17465294/100256232-226b4080-2f77-11eb-902e-f655f774a28c.png)

128 ![favico-ngecilin-128](https://user-images.githubusercontent.com/17465294/100256234-226b4080-2f77-11eb-8e13-59fafe45ab2c.png)

**Comment by empeje** [comment]
Thanks, mas @hudakurniawan we really appreciated it. It will be included in the next release.

**Comment by galanggg** [comment]
Hi all, i created a new PR for this issue #28 please kindly check it. Thanks

**Comment by empeje** [comment]
Solved in #28
